version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    environment:
      - START_XVFB=false
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      default:
        aliases:
          - selenium
  web:
    image: sdswart/streamlit_portal:latest
    env_file:
      - env.env
    command: bash -c "gunicorn --bind 0.0.0.0:8100 sp.wsgi"
    ports:
      - "8100-8200:8100-8200"
    volumes:
      - spstatic:/www/static
      - spinstance:/www/instance
    depends_on:
      - selenium
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      default:
        aliases:
          - web
  nginx:
    image:  sdswart/sp_nginx:latest
    volumes:
      - spstatic:/static
    depends_on:
      - web
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "1337:80"
      - "1338:81"
    networks:
      default:
        aliases:
          - nginx
volumes:
  spstatic:
  spinstance:
